### ISSUE TITLE
Not Working Linux - Debian 7.6 

### ISSUE THREAD

**Issue by ozkaya84** [PhilippBaranovskiy/owa_firefox_addon#1]
I cant run  addon on my linux .

My system;
Firefox : 30
Linux debian-Musti-HP 3.2.0-4-486 #1 Debian 3.2.60-1+deb7u3 i686 GNU/Linux

distro : kwheezy 1.6
![owa1](https://cloud.githubusercontent.com/assets/1906879/3856101/32f08d82-1ef0-11e4-9358-4fb6d3a507ce.jpg)
![owa2](https://cloud.githubusercontent.com/assets/1906879/3856102/32f9c5f0-1ef0-11e4-8caa-10a0b1a61c35.jpg)

**Comment by rockfield** [comment]
ozkaya84, does update from Nov 30 fix problems with your version?

**Comment by ozkaya84** [comment]
Counter is working. But it shows wrong number. ( duplicate ). I think it adds inbox unread messages twice time. ( maybe  it is releated about in "Favourites tab inbox".) . And I haven't notification pop up still . By the way I changed my distro , my new distro ubuntu 14.04 based.

Thank you.


![snapshot145](https://cloud.githubusercontent.com/assets/1906879/5736192/908e6064-9bdb-11e4-8bc2-d1cafa4b0a32.png)
